%% ----------------- SETTINGS -----------------
clear; clc; close all;

% Directories (Update these to match your path)
work_dir = 'C:\Users\Acer\Desktop\final year project\energy function\TEF_Framework\TEF_NE\Python Script';
result_dir = 'C:\Users\Acer\Desktop\final year project\energy function\TEF_Framework\TEF_NE\Matlab Script';

% Simulation Settings
t_fault = 1.0;      % Fault application time
t_cl    = 0.168;    % Clearing time
t_end   = 5.0;      % End time
del_t   = 0.001;    % TDS Step
del_t_fault = 0.001; 
del_t_BCU   = 0.01; 

num_bus = 39;
num_gen = 10;
plot_bus = 2; % Relative index (Generator 2, which is Bus 31)

%% ----------------- LOAD DATA -----------------
% 1. Load the Matrices generated by Python
if ~isfile(fullfile(result_dir, 'Y_all.mat'))
    error('Y_all.mat not found! Run the Python script first.');
end
load(fullfile(result_dir, 'Y_all.mat')); % Variables: Yint_pre, Yint_fault, Yint_post

% Ensure matrices are dense for MATLAB processing
Y_pre_kron   = full(Yint_pre);
Y_fault_kron = full(Yint_fault);
Y_post_kron  = full(Yint_post);

%% ----------------- SYSTEM PARAMETERS -----------------
% Generator Data (IEEE 39 Bus / New England)
% Indices: 30, 31, 32, 33, 34, 35, 36, 37, 38, 39
H = [500; 30.3; 35.8; 28.6; 26; 34.8; 26.4; 24.3; 34.5; 42];
D_gen = zeros(10,1); % Damping
M_gen = H ./ (pi * 60);
M_T   = sum(M_gen);

% Initial State (Voltages E and Angles delta)
% These serve as the "operating point".
% Note: We trust these Angles, but we will RECALCULATE Powers to match Y-bus.
E = [ 1.0562; 1.1782; 1.1507; 1.1004; 1.3594; 
      1.1806; 1.1288; 1.0721; 1.1382; 1.0215 ];

angleE = [ -0.0440; 0.3124; 0.3554; 0.3292; 0.6539; 
            0.3286; 0.3283; 0.3261; 0.5540; -0.1722 ];

Eeq_pre = E;
delpre  = angleE;

% --- CRITICAL FIX: Calculate Pm to match Y_pre_kron exactly ---
% Complex Voltage Vector
V_pre = E .* exp(1j * delpre);
% Current Injection I = Y * V
I_pre = Y_pre_kron * V_pre;
% Power Injection S = V * conj(I)
S_pre = V_pre .* conj(I_pre);
% Mechanical Power = Real(S) (Assuming lossless generator internal resistance)
Pgen_pre = real(S_pre); 
Pgen_post = Pgen_pre; % Assume constant mechanical power

disp('--- Power Flow Balance Check ---');
disp(['Calculated Pm (Total): ' num2str(sum(Pgen_pre))]);
disp('Using calculated Pm to ensure f(x0) = 0.');

% Initial COI setup
del0 = sum(delpre .* M_gen) / M_T;
delta_COI_pre = delpre - del0;
x_eq_pre = [delta_COI_pre; zeros(num_gen,1)]; % [delta; omega]

%% ----------------- PREPARE REDUCED MATRICES -----------------
% Helper to create G and B matrices for vector calculation
edge_kron = nchoosek(1:num_gen, 2);
n_edge = size(edge_kron, 1);
E_kron = zeros(n_edge, num_gen);

% Pre-allocate vectors
gij_pre = zeros(n_edge,1); bij_pre = zeros(n_edge,1);
gij_flt = zeros(n_edge,1); bij_flt = zeros(n_edge,1);
gij_pst = zeros(n_edge,1); bij_pst = zeros(n_edge,1);

for i = 1:n_edge
    u = edge_kron(i,1);
    v = edge_kron(i,2);
    E_kron(i, u) = 1;
    E_kron(i, v) = -1;
    
    % Extract Y components
    y_pre = Y_pre_kron(u,v);
    y_flt = Y_fault_kron(u,v);
    y_pst = Y_post_kron(u,v);
    
    % Pre-calculate transfer terms: V_i * V_j * Y_ij
    prod_E = E(u) * E(v);
    
    gij_pre(i) = real(y_pre) * prod_E; bij_pre(i) = imag(y_pre) * prod_E;
    gij_flt(i) = real(y_flt) * prod_E; bij_flt(i) = imag(y_flt) * prod_E;
    gij_pst(i) = real(y_pst) * prod_E; bij_pst(i) = imag(y_pst) * prod_E;
end

% Effective Power Injections (Pm - Gii*Ei^2)
P_pre_kron   = Pgen_pre  - real(diag(Y_pre_kron))  .* E.^2;
P_fault_kron = Pgen_post - real(diag(Y_fault_kron)).* E.^2;
P_post_kron  = Pgen_post - real(diag(Y_post_kron)) .* E.^2;

idx_delta = 1:num_gen;
idx_omega = num_gen+1 : 2*num_gen;
num_var   = 2*num_gen;

%% ----------------- DYNAMICS FUNCTIONS -----------------
% Generic Function Generator
get_f = @(x, P_k, bij_k, gij_k) ...
    [ x(idx_omega) - (M_gen'*x(idx_omega))/M_T; ... % COI Omega
      (1./M_gen) .* ( ...
          P_k ...
          - D_gen.*x(idx_omega) ...
          - E_kron' * (bij_k .* sin(E_kron * x(idx_delta))) ...
          - E_kron' * (gij_k .* cos(E_kron * x(idx_delta))) ...
      ) - (1/M_T) * (sum(P_k) - 2 * sum(gij_k .* cos(E_kron * x(idx_delta)))) ...
    ];

get_J = @(x, bij_k, gij_k) ...
    [ zeros(num_gen), eye(num_gen) - ones(num_gen,1)*M_gen'/M_T; ...
      (1./M_gen) .* ( ...
         - E_kron' * diag(bij_k .* cos(E_kron * x(idx_delta))) * E_kron ...
         + E_kron' * diag(gij_k .* sin(E_kron * x(idx_delta))) * E_kron ...
      ) - (2/M_T) * sum( (gij_k .* sin(E_kron*x(idx_delta))) .* E_kron, 1 ), ...
      -diag(D_gen./M_gen) ];

% Specific Dynamics
f_pre   = @(x) get_f(x, P_pre_kron,   bij_pre, gij_pre);
J_pre   = @(x) get_J(x, bij_pre,      gij_pre);

f_fault = @(x) get_f(x, P_fault_kron, bij_flt, gij_flt);
J_fault = @(x) get_J(x, bij_flt,      gij_flt);

f_post  = @(x) get_f(x, P_post_kron,  bij_pst, gij_pst);
J_post  = @(x) get_J(x, bij_pst,      gij_pst);

% Static Equations for SEP (Post-Fault)
% f(theta) = 0
f_static_post = @(th) ...
    P_post_kron ...
    - E_kron' * (bij_pst .* sin(E_kron * th)) ...
    - E_kron' * (gij_pst .* cos(E_kron * th)) ...
    - (M_gen/M_T) * (sum(P_post_kron) - 2*sum(gij_pst .* cos(E_kron * th)));

J_static_post = @(th) ...
    - E_kron' * diag(bij_pst .* cos(E_kron * th)) * E_kron ...
    + E_kron' * diag(gij_pst .* sin(E_kron * th)) * E_kron ...
    - (2./M_gen) * (M_gen * ( (gij_pst .* sin(E_kron*th))' * E_kron ) / M_T ) .* M_gen; 
    % Note: The Jacobian term for COI distribution is complex, simplified approx above usually works or use finite diff.
    % Let's use a simpler Jacobian construction for the static part to ensure robustness:
    
J_static_post_robust = @(th) ...
    - E_kron' * diag(bij_pst .* cos(E_kron * th)) * E_kron ...
    + E_kron' * diag(gij_pst .* sin(E_kron * th)) * E_kron;

%% ----------------- SOLVE POST-FAULT SEP -----------------
disp('Calculating Post-Fault SEP...');
theta_guess = x_eq_pre(idx_delta);

% Use Robust NR Solver
[theta_sep, converged] = Robust_NR(f_static_post, J_static_post_robust, theta_guess);

if ~converged
    error('Post-fault SEP did not converge. Check data consistency.');
end
x_eq_post = [theta_sep; zeros(num_gen,1)];
disp('SEP Found.');

%% ----------------- 1. TIME DOMAIN SIMULATION (TDS) -----------------
disp('Running TDS...');
num_sim_idx = ceil((t_end)/del_t) + 100;
x_sim = zeros(num_var, num_sim_idx); 
t_sim = zeros(1, num_sim_idx);
x_sim(:,1) = x_eq_pre; 
t_sim(1) = 0; 
t_idx = 1;

while t_sim(t_idx) <= t_end
    curr_t = t_sim(t_idx);
    curr_x = x_sim(:, t_idx);
    
    if curr_t < t_fault
        % Pre-fault
        h = del_t;
        fn = f_pre; Jn = J_pre;
    elseif curr_t < (t_fault + t_cl)
        % Fault-on
        h = del_t_fault;
        fn = f_fault; Jn = J_fault;
    else
        % Post-fault
        h = del_t;
        fn = f_post; Jn = J_post;
    end
    
    % Trapezoidal Integration Step
    % x_new = x_old + (h/2) * ( f(x_old) + f(x_new) )
    % Define residue G(y) = y - x_old - (h/2)*f(x_old) - (h/2)*f(y) = 0
    k = h/2;
    f_old = fn(curr_x);
    G = @(y) y - curr_x - k*f_old - k*fn(y);
    dG = @(y) eye(num_var) - k*Jn(y);
    
    % Solve for next step
    [x_next, ok] = Robust_NR(G, dG, curr_x + h*f_old); % Initial guess Euler
    
    if ~ok, disp(['TDS Integration failed at t=' num2str(curr_t)]); break; end
    
    x_sim(:, t_idx+1) = x_next;
    t_sim(t_idx+1) = curr_t + h;
    t_idx = t_idx + 1;
end

% Trim
t_sim = t_sim(1:t_idx);
x_sim = x_sim(:, 1:t_idx);

% Check Stability
max_angle_diff = max(max(x_sim(idx_delta, :)) - min(x_sim(idx_delta, :)));
is_stable_TDS = max_angle_diff < 2*pi;

%% ----------------- 2. PEBS METHOD -----------------
disp('Running PEBS...');
x_curr = x_eq_pre;
PEBS_idx = 0;
V_tot = []; t_pebs = [];

% V_pe at pre-fault equilibrium (Reference)
V_pe_base = -sum(P_post_kron .* (x_eq_pre(idx_delta) - x_eq_post(idx_delta))) ...
            -sum(bij_pst .* (cos(E_kron*x_eq_pre(idx_delta)) - cos(E_kron*x_eq_post(idx_delta)))) ...
            +sum( (gij_pst .* (cos(E_kron*x_eq_pre(idx_delta)) + cos(E_kron*x_eq_post(idx_delta))) ) .* (E_kron*(x_eq_pre(idx_delta)-x_eq_post(idx_delta))) ) * 0.5;
% Note: The path dependent term approximation is used in standard PEBS.
% Simplified PEBS usually integrates potential energy along the fault trajectory.

max_steps = 2000;
pebs_cross = false;
tcr_PEBS = 0;

for k = 1:max_steps
    % Integrate Fault Trajectory
    h = del_t_fault;
    f_old = f_fault(x_curr);
    G = @(y) y - x_curr - (h/2)*f_old - (h/2)*f_fault(y);
    dG = @(y) eye(num_var) - (h/2)*J_fault(y);
    [x_next, ok] = Robust_NR(G, dG, x_curr + h*f_old);
    
    if ~ok, break; end
    
    % Calculate PEBS function (Directional Derivative of PE)
    % f_post_theta(theta)' * (theta - theta_sep)
    f_val = f_static_post(x_next(idx_delta));
    pebs_val = f_val' * (x_next(idx_delta) - x_eq_post(idx_delta));
    
    if k > 1 && pebs_val > 0 && last_pebs_val < 0
        % Crossing detected
        tcr_PEBS = (k-1) * del_t_fault;
        pebs_cross = true;
        break;
    end
    
    last_pebs_val = pebs_val;
    x_curr = x_next;
end
disp(['PEBS CCT Estimate: ' num2str(tcr_PEBS)]);

%% ----------------- 3. BCU METHOD (Conceptual) -----------------
% Full BCU is complex. Using the PEBS crossing point as the starting guess for the "Exit Point".
% Then solving reduced gradient system.
% For this snippet, we will rely on the Hybrid/TDS refinement as it's more practical for immediate results.

%% ----------------- 4. HYBRID REFINEMENT -----------------
disp('Running Hybrid Refinement...');
% Binary search using TDS to find exact CCT
t_lb = 0.05; 
t_ub = 0.30; 
if tcr_PEBS > 0, t_ub = tcr_PEBS + 0.05; end

for iter = 1:10
    t_try = (t_lb + t_ub)/2;
    
    % Quick TDS
    x_hyb = x_eq_pre;
    curr_t = 0;
    stable = true;
    
    while curr_t < 3.0 % Run for 3 seconds
        if curr_t < t_fault
            fn = f_pre; h=0.01;
        elseif curr_t < t_fault + t_try
            fn = f_fault; h=0.002;
        else
            fn = f_post; h=0.01;
        end
        % Euler for speed in hybrid search
        x_hyb = x_hyb + h * fn(x_hyb);
        curr_t = curr_t + h;
        
        if max(x_hyb(idx_delta)) - min(x_hyb(idx_delta)) > 2*pi
            stable = false; break;
        end
    end
    
    if stable
        t_lb = t_try;
    else
        t_ub = t_try;
    end
end
tcr_Hybrid = t_lb;

%% ----------------- PLOTTING -----------------
figure('Color','w');
subplot(2,1,1);
plot(t_sim, x_sim(idx_delta, :) * 180/pi);
ylabel('Angles (deg)'); xlabel('Time (s)');
title(['Response for t_{cl} = ' num2str(t_cl) 's']);
grid on;

subplot(2,1,2);
plot(t_sim, x_sim(idx_omega, :));
ylabel('Speed (rad/s)'); xlabel('Time (s)');
grid on;

disp(' ');
disp(['Final CCT (Hybrid): ' num2str(tcr_Hybrid) ' s']);

%% ----------------- HELPER: ROBUST NR SOLVER -----------------
function [x, converged] = Robust_NR(Fun, Jac, x0)
    x = x0;
    converged = false;
    max_iter = 50;
    tol = 1e-6;
    lambda = 1.0; % Damping factor
    
    for i = 1:max_iter
        F = Fun(x);
        err = norm(F, inf);
        if err < tol
            converged = true;
            return;
        end
        
        J = Jac(x);
        
        % Check for singular matrix
        if rcond(J) < 1e-12
            dx = pinv(J) * -F; % Use pseudo-inverse if singular
        else
            dx = J \ -F;
        end
        
        % Simple Damping line search check
        x_new = x + lambda * dx;
        if norm(Fun(x_new), inf) > err
             % If error increases, reduce step
             x_new = x + 0.5 * lambda * dx;
        end
        x = x_new;
    end
    
    % Final check
    if norm(Fun(x), inf) < 1e-3 % Relaxed tolerance for final check
        converged = true;
    end
end